Vagrant.configure(2) do |config|

  # Use the same key for each machine
  config.ssh.insert_key = false

  config.vm.provision "shell", inline: $script

  config.vm.define "elasticsearch" do |elasticsearch|
    elasticsearch.vm.box = "centos/7"
    elasticsearch.vm.network "private_network", ip: "192.168.56.10"
    elasticsearch.vm.network "forwarded_port", guest: 9200, host: 9200
    elasticsearch.vm.network "forwarded_port", guest: 9300, host: 9300
    elasticsearch.vm.network = "elasticsearch"
    elasticsearch.vm.provider "virtualbox" do |vb|
      vb.name = "elasticsearch"
      vb.gui = false
      vb.memory = "2048"
    end
  end
  config.vm.define "logstash" do |logstash|
    logstash.vm.box = "centos/7"
    logstash.vm.network "private_network", ip: "192.168.56.11"
    logstash.vm.network "forwarded_port", guest: 5044, host: 5044
    logstash.vm.hostname = "logstash"
    logstash.vm.provider "virtualbox" do |vb|
      vb.name = "logstash"
      vb.gui = false
      vb.memory = "1024"
    end
  end
  config.vm.define "kibana" do |kibana|
    kibana.vm.box = "centos/7"
    kibana.vm.network "private_network", ip: "192.168.56.12"
    kibana.vm.network "forwarded_port", guest: 5601, host: 5601
    kibana.vm.hostname = "kibana"
    kibana.vm.provider "virtualbox" do |vb|
      vb.name = "kibana"
      vb.gui = false
      vb.memory = "1024"
    end
  end
  config.vm.define "grafana" do |grafana|
    grafana.vm.box = "centos/7"
    grafana.vm.network "private_network", ip: "192.168.56.13"
    grafana.vm.network "forwarded_port", guest: 3000, host: 3000
    grafana.vm.hostname = "grafana"
    grafana.vm.provider "virtualbox" do |vb|
      vb.name = "grafana"
      vb.gui = false
      vb.memory = "1024"
    end
  end
  config.vm.define "nginx" do |nginx|
    nginx.vm.box = "centos/7"
    nginx.vm.network "private_network", ip: "192.168.56.14"
    nginx.vm.network "forwarded_port", guest: 8080, host: 8080
    nginx.vm.hostname = "nginx"
    nginx.vm.provider "virtualbox" do |vb|
      vb.name = "nginx"
      vb.gui = false
      vb.memory = "1024"
    end
  end
end


$script = <<-SCRIPT
yum install -y epel-release
yum clean all && yum makecache
yum -y update
yum install -y mc wget curl zip tree vim-enhanced java-1.8.0-openjdk
SCRIPT
