Vagrant.configure(2) do |config|

  # Use the same key for each machine
  config.ssh.insert_key = false

  config.vm.provision "shell", inline: $script

  config.vm.define "psql01" do |psql01|
    psql01.vm.box = "centos/7"
    psql01.vm.network "private_network", ip: "192.168.56.111"
    psql01.vm.provider "virtualbox" do |vb|
      vb.name = "psql01"
      vb.gui = false
      vb.memory = "1024"
    end
  end
  config.vm.define "psql02" do |psql02|
    psql02.vm.box = "centos/7"
    psql02.vm.network "private_network", ip: "192.168.56.112"
    psql02.vm.provider "virtualbox" do |vb|
      vb.name = "psql02"
      vb.gui = false
      vb.memory = "1024"
    end
  end
  config.vm.define "grafana01" do |grafana01|
    grafana01.vm.box = "centos/7"
    grafana01.vm.network "private_network", ip: "192.168.56.113"
    grafana01.vm.provider "virtualbox" do |vb|
      vb.name = "grafana01"
      vb.gui = false
      vb.memory = "2048"
    end
  end
  config.vm.define "backup" do |backup|
    backup.vm.box = "centos/7"
    backup.vm.network "private_network", ip: "192.168.56.114"
    backup.vm.provider "virtualbox" do |vb|
      vb.name = "backup"
      vb.gui = false
      vb.memory = "1024"
    end
  end
end


$script = <<-SCRIPT
yum install -y epel-release
yum clean all && yum makecache
yum update
yum install -y mc wget curl zip tree vim-enhanced
SCRIPT
