Vagrant.configure("2") do |config|
  config.vm.define "ubuntu01" do |vm1|
    vm1.vm.hostname = "ubuntu01"
    vm1.vm.box = "bento/ubuntu-20.04"
    vm1.vm.network "private_network", ip: "192.168.56.4"
    vm1.vm.network "private_network", ip: "192.168.56.5"
#  config.vm.network "public_network", type: "dhcp", bridge: "eth0"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu01"
      vb.gui = false
      vb.memory = "1024"
    end
  end
  config.vm.define "ubuntu02" do |vm2|
    vm2.vm.hostname = "ubuntu02"
    vm2.vm.box = "bento/ubuntu-20.04"
    vm2.vm.network "private_network", ip: "192.168.56.41"
    vm2.vm.network "private_network", ip: "192.168.56.51"
#  config.vm.network "public_network", type: "dhcp", bridge: "eth0"
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu02"
      vb.gui = false
      vb.memory = "1024"
    end
  end
end
