all: # keys must be unique, i.e. only one 'hosts' per group
  hosts:
  children:   # key order does not matter, indentation does
    vmagent:
      hosts:
        vmagent1: { ansible_host: "127.0.0.1" ansible_port: "2222" ansible_user: "vagrant" ansible_become_user: "root" }
        vmagent2: { ansible_host: "127.0.0.1" ansible_port: "2200" ansible_user: "vagrant" ansible_become_user: "root" }
        vmagent3: {ansible_host: "127.0.0.1" ansible_port: "2202" ansible_user: "vagrant" ansible_become_user: "root" }
