Vagrant.configure(2) do |config|

  # Use the same key for each machine
  config.ssh.insert_key = false

  config.vm.provision "shell", inline: $script

  config.vm.define "cent01" do |cent01|
    cent01.vm.box = "centos/7"
    cent01.vm.network "private_network", ip: "192.168.56.101"
    cent01.vm.network "forwarded_port", guest: 9090, host: 9090
    cent01.vm.provider "virtualbox" do |vb|
      vb.name = "centvm01"
      vb.gui = false
      vb.memory = "1024"
    end
  end
  config.vm.define "cent02" do |cent02|
    cent02.vm.box = "centos/7"
    cent02.vm.network "private_network", ip: "192.168.56.102"
    cent02.vm.provider "virtualbox" do |vb|
      vb.name = "centvm02"
      vb.gui = false
      vb.memory = "1024"
    end
  end
  config.vm.define "cent03" do |cent03|
    cent03.vm.box = "centos/7"
    cent03.vm.network "private_network", ip: "192.168.56.103"
    cent03.vm.network "forwarded_port", guest: 9100, host: 9100
    cent03.vm.provider "virtualbox" do |vb|
      vb.name = "centvm03"
      vb.gui = false
      vb.memory = "1024"
    end
  end
  config.vm.define "cent04" do |cent04|
    cent04.vm.box = "centos/7"
    cent04.vm.network "private_network", ip: "192.168.56.104"
    cent04.vm.network "forwarded_port", guest: 9091, host: 9091
    cent04.vm.provider "virtualbox" do |vb|
      vb.name = "centvm04"
      vb.gui = false
      vb.memory = "1024"
    end
  end
  config.vm.define "cent05" do |cent05|
    cent05.vm.box = "centos/7"
    cent05.vm.network "private_network", ip: "192.168.56.105"
    cent05.vm.network "forwarded_port", guest: 9093, host: 9093
    cent05.vm.provider "virtualbox" do |vb|
      vb.name = "centvm05"
      vb.gui = false
      vb.memory = "1024"
    end
  end
end


$script = <<-SCRIPT
yum install -y epel-release
yum clean all && yum makecache
yum update
yum install -y mc wget curl zip tree vim-enhanced
SCRIPT
